### ISSUE TITLE
Please use Class name prefix in the Source Code sections

### ISSUE THREAD

**Issue by foal** [DominoKit/domino-ui-demo#22]
Right now, the Source Code sections contain the code samples without class names

e.g. https://dominokit.com/domino-ui/demo/v2/typography

![image](https://github.com/DominoKit/domino-ui-demo/assets/458209/c9d50c7e-d6db-4ec8-beda-be06c0cb44e4)

Please, use for tutorial static methods/constant **with** class name.

**Comment by vegegoku** [comment]
Since now we have the new website with a much better documentation we prefer that you use the website for samples and documentations, for example : 
https://dominokit.com/solutions/domino-ui/v2/docs/typography

Now notice that not only we provide extra documentation there, but also the source code for the sample is a fully working domino-ui component that you can copy and use directly in your app, including all the imports. 

It is the effort and time that we are currently focus in other areas that is stopping us from refactoring the demo app from sharing the same samples from the website, later the code from the demo will be removed and links to the samples in the website will be provided for each demo page, this way we can keep the demo app in sync without duplicating the efforts.

**Comment by foal** [comment]
Thank you! It is better, but...
 
1. Direct link doesn't work 
![image](https://github.com/DominoKit/domino-ui-demo/assets/458209/cad81ffa-dfb3-4580-9519-f35c137e92a1)
2. The source code view is too narrow  
![image](https://github.com/DominoKit/domino-ui-demo/assets/458209/020e8a05-8c35-4299-a9e7-766e2a2a097c)
3. Not sure about style references. Are they from?
![image](https://github.com/DominoKit/domino-ui-demo/assets/458209/bb3c67b0-119f-48bc-847e-9e5bec2e983d)

**Comment by vegegoku** [comment]
the first and last point are fixed, for the 2nd one I am not sure you seems to have a very narrow screen or maybe you have zoom enabled, but even in my smallest screen it is still wider than that, still I dont think there is a lot I can do about this that would solve it entirely, but most of the samples are made so that you can just copy them into any text editor or directly into your IDE where you can vie and inspect the code.

**Comment by foal** [comment]
Hmm. I have zoom enabled (200% and 150%). But if I switch to 100% the wide of source section is Ok. But all other (system) is too small :)
![image](https://github.com/DominoKit/domino-ui-demo/assets/458209/1212cb46-1e40-4501-aedc-77125122943f)

For 150% it is Ok but there is some space to make it wide
![image](https://github.com/DominoKit/domino-ui-demo/assets/458209/b40d38e8-4b82-46cc-a229-c9788ef6ca73)
